name: Build_Clang13

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 30 7 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Build_Clang13:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E snap set system refresh.retain=2
        sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu*
        sudo -E apt-get -y autoremove --purge
        sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
        [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python3-dev haveged lrzsz device-tree-compiler scons bc bison ca-certificates clang cmake file gcc g++ ninja-build lld make u-boot-tools xz-utils binutils-dev
        wget -qO - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | sed 's/python-/python3-/g' | /bin/bash
        sudo -E apt-get clean
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
        df -h
        
    - name: Clone source code and  Build
      env: 
        REPO_URL: https://github.com/xiangfeidexiaohuo/tc-build
        REPO_BRANCH: personal
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH tc-build
        cd tc-build
        cp -f ../diy/diy_clang.sh ./
        chmod +x ./diy_clang.sh && ./diy_clang.sh
       
    - name: Assemble Artifact
      id: assemble_artifact
      run: |
        rm -rf ./Clang_Out
        mkdir -p ./Clang_Out/
        mv tc-build/clang-tmp ./Clang_Out/clang-$(date +%Y%m%d)
        mv tc-build/binutils-tmp ./Clang_Out/binutils-$(date +%Y%m%d)
        cd Clang_Out
        echo "AE86-Clang v14.0.0-$(date +%Y%m%d)-YaoDao" > VERSION
        mv VERSION ./clang-$(date +%Y%m%d)/
        tar zcvf AE86-Clang14-$(date +%Y%m%d).tar.gz clang-$(date +%Y%m%d)/*
        tar zcvf AE86-binutils-$(date +%Y%m%d).tar.gz binutils-$(date +%Y%m%d)/*
                                
               
    - name: Upload Clang
      uses: actions/upload-artifact@main
      with:
        name: Compiler-Tools
        path: Clang_Out/*.tar.gz 

#    - name: Generate Tag & Release Name
#      id: generate_name
#      run: |
#        time=$(date +%Y%m%d%H%M)
#        release_tag="$time"
#        release_name="Compiler-Tools-$(date +%Y%m%d)"
#        echo "##[set-output name=release_name;]$release_name"
#        echo "##[set-output name=release_tag;]$release_tag"        

#    - name: Create Release & Upload
#      uses: ncipollo/release-action@v1
#      with:
#        artifacts: Clang_Out/*.tar.gz 
#        name: ${{ steps.generate_name.outputs.release_name }}
#        tag: ${{ steps.generate_name.outputs.release_tag }}
#        token: ${{ secrets.GITHUB_TOKEN }}
                 
